blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/muhittincamdali/SwiftUI-Gesture-Library#readme
    about: Check out the documentation first
  - name: ðŸ’¬ Discussions
    url: https://github.com/muhittincamdali/SwiftUI-Gesture-Library/discussions
    about: Ask questions and discuss ideas
